name: Docker Image private

on:
  push:
    branches: [ private ]
  pull_request:
    branches: [ private ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps: 
    
    - name: Check out the repo
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Docker Build & Push to Docker Hub 
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./yopngs/Dockerfile
        platforms: linux/amd64
        push: true
        tags: xpnas/yopngs:private

    - name: 'Report Suecss'
      run: curl ${{ secrets.INOTIFY }}/yopngs/privateIsOk!
